=== Claug19/ShowroomXML/src/main/resources/showroom.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Data" type="DataType">
    <xs:annotation>
      <xs:documentation> Describes information in a car dealer showroom </xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:complexType name="ClientType">
    <xs:sequence>
      <xs:element name="firstName">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="John"/>
            <xs:enumeration value="Gordon"/>
            <xs:enumeration value="Mary"/>
            <xs:enumeration value="Walter"/>
            <xs:enumeration value="Gunar"/>
            <xs:enumeration value="Wilhelm"/>
            <xs:enumeration value="Ann"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="lastName">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Johnson"/>
            <xs:enumeration value="Ramsay"/>
            <xs:enumeration value="White"/>
            <xs:enumeration value="Ferguson"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="preferredCar" maxOccurs="unbounded" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Opel"/>
            <xs:enumeration value="Dacia"/>
            <xs:enumeration value="Mercedes"/>
            <xs:enumeration value="Audi"/>
            <xs:enumeration value="Volvo"/>
            <xs:enumeration value="Seat"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="filter" maxOccurs="unbounded" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="SUV"/>
            <xs:enumeration value="10000"/>
            <xs:enumeration value="test"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="xs:string" name="currency"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="optional"/>
    <xs:attribute type="xs:string" name="familyId" use="optional"/>
    <xs:attribute type="xs:string" name="gender" use="optional"/>
  </xs:complexType>
  <xs:complexType name="ClientsType">
    <xs:sequence>
      <xs:element type="ClientType" name="Client" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="DiscountType">
    <xs:sequence>
      <xs:element name="expirationDate">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="2022-10-30"/>
            <xs:enumeration value="2022-04-01"/>
            <xs:enumeration value="2021-12-31"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="value">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="10"/>
            <xs:enumeration value="5"/>
            <xs:enumeration value="15"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
    <xs:attribute type="xs:string" name="idRef" use="optional"/>
  </xs:complexType>
  <xs:complexType name="DiscountsType">
    <xs:sequence>
      <xs:element type="DiscountType" name="Discount" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="priceType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="currency" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="featuresType">
    <xs:sequence>
      <xs:element name="feature" maxOccurs="unbounded" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Airbag"/>
            <xs:enumeration value="Heated seat"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CarType">
    <xs:sequence>
      <xs:element name="carBrand">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Volvo"/>
            <xs:enumeration value="Dacia"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="model">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="xc90"/>
            <xs:enumeration value="Logan"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="type">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="SUV"/>
            <xs:enumeration value="sedan"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="consumption">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Benzine"/>
            <xs:enumeration value="Diesel"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="year">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="2020"/>
            <xs:enumeration value="2018"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element type="priceType" name="price"/>
      <xs:element type="featuresType" name="features"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="carId" use="optional"/>
  </xs:complexType>
  <xs:complexType name="AvailableCarsType">
    <xs:sequence>
      <xs:element type="CarType" name="Car" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ReservedCarType">
    <xs:sequence>
      <xs:element type="xs:string" name="clientId"/>
      <xs:element type="xs:string" name="carId"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ReservedCarsType">
    <xs:sequence>
      <xs:element type="ReservedCarType" name="ReservedCar"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="DataType">
    <xs:sequence>
      <xs:element type="ClientsType" name="Clients">
        <xs:annotation>
          <xs:documentation> clients </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="DiscountsType" name="Discounts">
        <xs:annotation>
          <xs:documentation> Discounts the clients have </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="AvailableCarsType" name="AvailableCars">
        <xs:annotation>
          <xs:documentation> Cars available in the showroom </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="ReservedCarsType" name="ReservedCars">
        <xs:annotation>
          <xs:documentation> Reserved cars</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Claug19/ShowroomXML/src/main/resources/showroom.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!-- Describes information in a car dealer showroom --><Data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="showroom.xsd">
    <!-- clients -->
    <Clients>
        <Client familyId="022" gender="male" id="1">
            <firstName>John</firstName>
            <lastName>Johnson</lastName>
            <preferredCar>Opel</preferredCar>
            <preferredCar>Dacia</preferredCar>
            <filter>SUV</filter>
            <currency>euro</currency>
        </Client>
        <Client familyId="050" gender="male" id="2">
            <firstName>Gordon</firstName>
            <lastName>Ramsay</lastName>
            <preferredCar>Mercedes</preferredCar>
            <currency>euro</currency>
        </Client>
        <Client familyId="022" gender="female" id="3">
            <firstName>Mary</firstName>
            <lastName>Johnson</lastName>
            <preferredCar>Audi</preferredCar>
            <currency>euro</currency>
        </Client>
        <Client familyId="003" gender="male" id="4">
            <firstName>Walter</firstName>
            <lastName>White</lastName>
            <preferredCar>Audi</preferredCar>
            <preferredCar>Mercedes</preferredCar>
            <currency>euro</currency>
        </Client>
        <Client familyId="025" gender="male" id="5">
            <firstName>Gunar</firstName>
            <lastName>Ferguson</lastName>
            <preferredCar>Volvo</preferredCar>
            <filter>SUV</filter>
            <filter>10000</filter>
            <filter>test</filter>
            <currency>euro</currency>
        </Client>
        <Client familyId="030" gender="male" id="6">
            <firstName>Wilhelm</firstName>
            <lastName>Johnson</lastName>
            <preferredCar>Seat</preferredCar>
            <currency>euro</currency>
        </Client>
        <Client familyId="030" gender="female" id="7">
            <firstName>Ann</firstName>
            <lastName>Johnson</lastName>
            <preferredCar>Seat</preferredCar>
            <currency>euro</currency>
        </Client>
    </Clients>
    <!-- Discounts the clients have -->
    <Discounts>
        <Discount idRef="1">
            <expirationDate>2022-10-30</expirationDate>
            <value>10</value>
        </Discount>
        <Discount idRef="3">
            <expirationDate>2022-04-01</expirationDate>
            <value>5</value>
        </Discount>
        <Discount idRef="5">
            <expirationDate>2021-12-31</expirationDate>
            <value>15</value>
        </Discount>
    </Discounts>
    <!-- Cars available in the showroom -->
    <AvailableCars>
        <Car carId="300">
            <carBrand>Volvo</carBrand>
            <model>xc90</model>
            <type>SUV</type>
            <consumption>Benzine</consumption>
            <year>2020</year>
            <price currency="euro">11765</price>
            <features>
                <feature>Airbag</feature>
                <feature>Heated seat</feature>
            </features>
        </Car>
        <Car carId="301">
            <carBrand>Dacia</carBrand>
            <model>Logan</model>
            <type>sedan</type>
            <consumption>Benzine</consumption>
            <year>2018</year>
            <price currency="euro">10000</price>
            <features>
                <feature>Airbag</feature>
                <feature>Heated seat</feature>
            </features>
        </Car>
        <Car carId="302">
            <carBrand>Dacia</carBrand>
            <model>Logan</model>
            <type>sedan</type>
            <consumption>Diesel</consumption>
            <year>2018</year>
            <price currency="dollar">8000</price>
            <features>
                <feature>Airbag</feature>
                <feature>Heated seat</feature>
            </features>
        </Car>
        <Car carId="303">
            <carBrand>Seat</carBrand>
            <model>Leon</model>
            <type>sedan</type>
            <consumption>Diesel</consumption>
            <year>2010</year>
            <price currency="dollar">5000</price>
            <features>
                <feature>Airbag</feature>
                <feature>Heated seat</feature>
            </features>
        </Car>
    </AvailableCars>

    <!-- Reserved cars-->
    <ReservedCars>
        <ReservedCar>
            <clientId>1</clientId>
            <carId>302</carId>
        </ReservedCar>
   </ReservedCars>
</Data>
